### ISSUE TITLE
Arch-independent library directory support

### ISSUE THREAD

**Issue by tambry** [TheLartians/PackageProject.cmake#30]
Currently `CMAKE_INSTALL_LIBDIR` is used for the installation, e.g. `/usr/lib/x86-64-linux-gnu`. However, for arch-independent packages the files should go into `/usr/lib` (`${CMAKE_INSTALL_PREFIX}/lib`).

**Comment by Arniiiii** [comment]
Nope. 
The files for include should go to `include`
for cmake configs should go to `share/cmake/${PROJECT_NAME}`

Because if cmake configs are going to `lib` or `lib64`, then if there's a multilib environment, libs from 32-bit environment won't see cmake configs installed to lib64, and vice versa.

Actually it a bug that if ARCH_INDEPENDENT, then it installs cmake configs to `lib` or `lib64` , but not to an ABI-independent folder such as `share/cmake/${PROJECT_NAME}`
